obj-$(CONFIG_AURALIC_IRKEY)     += auralic_irkey.o auralic_irkey_vega.o
obj-$(CONFIG_AURALIC_CONTROL) += auralic_control.o
obj-$(CONFIG_AURALIC_I2C)        += auralic_i2c.o 
obj-$(CONFIG_AURALIC_SYS)        += auralic_sys.o auralic_sys_vega.o
obj-$(CONFIG_AURALIC_LCD)        += auralic_lcd.o 
obj-$(CONFIG_AURALIC_ES9028PRO)        += auralic_es9028pro.o auralic_volume_control.o 
obj-$(CONFIG_AURALIC_FILELIST)        += auralic_filelist.o 
